### PR TITLE
GET /peace

### LINKED ISSUE #6: Peace
The following request should make DJ54B disable playback for 60 minutes:

```
GET /peace
```

During this period, all other requests are ignored (including further `/peace` requests).

/cc @timharding

### PR DESCRIPTION
**Pull request by jgwhite**
- [x] Touch peacefile on `GET /peace`
- [x] Actually pause the tunes too!

Closes #6

### CODE REVIEW

**Comment by jgwhite** [comment]
FAO @timharding

**Comment by erino** [comment]
This shouldn't be a `GET` as it has a side effect, what about `POST` or `PUT`?

**Comment by jgwhite** [comment]
@erino DJ54B is not a RESTful API

**Comment by jgwhite** [comment]
:trollface:

**Pull request merged**
